package Application;
import java.awt.Point;
import java.util.ArrayList;
import java.util.List;

/**
 * This class is a dummy example class generated by professor Louis Conover for the GUI team to use to store the graphics till
 * the database team provides us with the actual class for database.
 * 
 * This class has been completely copied by the demo provided by the professor and it is not written or maintained by the GUI team
 * 
 * @author LOUIS CONOVER
 *
 */
class DB {
	List<Point[]> db;
	int size;

	DB () {
		db = new ArrayList<Point[]>(10);
		size = 0;
	}
	
	public void Add (Point[] p) {
		db.add(p);
		size++;
	}
	
	public Point[] Get (int i ) {
		return db.get(i);
	}
	
	public int Size () {
		return size;
	}
	
	/**
	 * written 3/13/18 by Jaemarie Solyst
	 * @param i takes in index of shape array to be deleted
	 * @return the shape array that was deleted
	 */
	public Point[] delete(int i) {
		
		//make sure that the int is not out of bounds
		if (i < size && i >= 0) {
			//Get a clone to return
			Point[] deletedShape = db.get(i).clone();
			
			//Remove the shapeArray from the db and return the clone
			db.remove(i);
			
			//Decrement the size
			size--;
			return deletedShape;
		}
		return null;
	}
	
	//ADDED BY IOANNA DENI 3/21/2018
		public Point[] returnPoint () {
			
			if (size!=0){
				return db.get(size-1);
			}
			else{
				return null;
			}
		}
}
